### ISSUE TITLE
效能提升的方式

### ISSUE THREAD

**Issue by ren1244** [nk2028/opencc-js#2]
javascript 的 object 只能用字串作為 key，導致每次搜尋時都要切割出子字串，對於大量文字的文章來說是負擔是比較重的。
我在[自己的專案](https://github.com/ren1244/quick-opencc-js)用 [Map物件](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Global_Objects/Map) 實作，然後以 unicode 的數值作為 key。在查詢時不切割字串，而是用 codePointAt 來取得key，測試出來效能提升會超過3倍。

**Comment by sgalal** [comment]
感謝指出！請問是否願意將 quick-opencc-js 的內容合入本專案？我可以將閣下添加為維護者

**Comment by ren1244** [comment]
可以，只是我程式碼是另外寫的，不知道合過來會動到多少。
另外其實我不是很了解合過來的話，實際上我需要做甚麼，這是我第一次參與別的專案。
