### ISSUE TITLE
Usecase for newbies

### ISSUE THREAD

**Issue by hugolpz** [nk2028/opencc-js#9]
Hello, I created a [jsffidle](https://jsfiddle.net/jkwr8xpa/11/) to test few usecases from your readme.md. I was partially successful.

The convert page content script didn't work :
```js
((async () => {
  const convert = await OpenCC.Converter('hk', 'cn');
  const startNode = document.documentElement; // Convert the whole page
  const HTMLConvertHandler = OpenCC.HTMLConverter(convert, startNode, 'zh-HK', 'zh-CN'); // Convert all zh-HK to zh-CN
  HTMLConvertHandler.convert(); // Start conversion
  HTMLConvertHandler.restore(); // Restore
})());
```

I tried to assign to variable but also failed. (but this one is likely on me since I don't understand asyn well).

It could be interesting for users to have some usecases working on fiddle as demos.

**Comment by sgalal** [comment]
I have updated the API. Now there is no `async` any more. Would you please see if this would be easier?

**Comment by hugolpz** [comment]
Hello Sgalal, thanks for the quick reply and REAME.md rewrite : ).

Few things:
- I tested again [on this pad](https://jsfiddle.net/9vLwm2zf/), I wasn't able to make it works.
- Seems `<script src="https://cdn.jsdelivr.net/npm/opencc-js@1.0.1/data.min.js"></script>` drops an error. If I include this file twice, we get two errors.
- On the readme, we can do shorter. Will do a PR.

**Comment by sgalal** [comment]
This will work:

```html
<script src="https://cdn.jsdelivr.net/npm/opencc-js@1.0.1/data.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/opencc-js@1.0.1/data.cn2t.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/opencc-js@1.0.1/data.t2cn.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/opencc-js@1.0.1/bundle-browser.min.js"></script>

<div id="testingOpenCC" lang="zh-HK">
  <span>轉換整個頁面</span>
</div>
```

```javascript
document.addEventListener('DOMContentLoaded', () => {
  const converter = OpenCC.Converter({ from: 'hk', to: 'cn' });
  const rootNode = document.documentElement;
  const HTMLConvertHandler = OpenCC.HTMLConverter(converter, rootNode, 'zh-HK', 'zh-CN');
  HTMLConvertHandler.convert();
});
```

**Comment by sgalal** [comment]
`{ from: 'hk', to: 'cn' }` affects the OpenCC conversion, while `'zh-HK', 'zh-CN'` affects the lang attribute of HTML tags

Both are necessary because we can have multiple combinations like:

- `{ from: 'tw', to: 'cn' }` + `'zh-TW', 'zh-CN'`
- `{ from: 'twp', to: 'cn' }` + `'zh-TW', 'zh-CN'`
- `{ from: 'tw', to: 'cn' }` + `'cmn-TW', 'cmn-CN'`
- `{ from: 'twp', to: 'cn' }` + `'cmn-TW', 'cmn-CN'`
- `{ from: 'tw', to: 'cn' }` + `'nan-TW', 'nan-CN'`
- `{ from: 'twp', to: 'cn' }` + `'nan-TW', 'nan-CN'`
- `{ from: 'tw', to: 'cn' }` + `'nan-Hant-TW', 'nan-Hans-CN'`
- ...

**Comment by hugolpz** [comment]
I see that one feeds into OpenCC javascript, the other into html attribute `lang`. 

Not sure, but seems...
* JS : defines the direction + default or is `p`.
* HTML attribute lang : defines a language and script, with associated vocabulary list (cn: 自行车/自行車 -> tw: 脚踏车/腳踏車).

**Comment by sgalal** [comment]
> I was unable to make sections 2, 3, 4 works. See fiddle.

The usage is modified (see README)

**Comment by hugolpz** [comment]
I think the readme is better now and suits the newbies' need requested above : we can indeed copy-paste and convert a page or section of page. This issue can be closed. 👍🏼 

Scope limit could be better stated depending on the limits you want to fix.
Being able to convert string and save value on demand would expand possible usages.
